export default {
  id: 753871008,
  id_str: '753871008',
  name: 'Simon vom Eyser',
  screen_name: 'simonvomeyser',
  location: 'Nordrhein-Westfalen',
  description:
    'web dev and musician from NRW, Germany. Javascript and PHP, React and Laravel productivity and tooling, coffee and (dev)humor 😎',
  url: 'https://t.co/o4snCI8YWw',
  protected: false,
  followers_count: 58,
  friends_count: 430,
  listed_count: 3,
  created_at: 'Sun Aug 12 22:08:01 +0000 2012',
  favourites_count: 276,
  utc_offset: -28800,
  time_zone: 'Pacific Time (US & Canada)',
  geo_enabled: false,
  verified: false,
  statuses_count: 96,
  contributors_enabled: false,
  is_translator: false,
  is_translation_enabled: false,
  profile_background_color: '000000',
  profile_background_image_url:
    'http://abs.twimg.com/images/themes/theme1/bg.png',
  profile_background_image_url_https:
    'https://abs.twimg.com/images/themes/theme1/bg.png',
  profile_background_tile: false,
  profile_image_url:
    'http://pbs.twimg.com/profile_images/763061093187059712/rBBWw17O_normal.jpg',
  profile_image_url_https:
    'https://pbs.twimg.com/profile_images/763061093187059712/rBBWw17O_normal.jpg',
  profile_link_color: '1B95E0',
  profile_sidebar_border_color: '000000',
  profile_sidebar_fill_color: '000000',
  profile_text_color: '000000',
  profile_use_background_image: false,
  has_extended_profile: false,
  default_profile: false,
  default_profile_image: false,
  following: null,
  follow_request_sent: null,
  notifications: null,
  translator_type: 'none',
};
