export default {
  bio: '',
  bioHTML: '',
  company: 'String',
  companyHTML: 'String',
  createdAt: 'String',
  email: 'String',
  id: 1,
  isBountyHunter: true,
  isCampusExpert: true,
  isDeveloperProgramMember: true,
  isEmployee: true,
  isHireable: true,
  isSiteAdmin: true,
  isViewer: true,
  location: 'String',
  login: 'String',
  name: 'String',
  resourcePath: 'String',
  updatedAt: 'String',
  url: 'String',
  viewerCanFollow: true,
  viewerIsFollowing: true,
  websiteUrl: 'String',
};
